version: '3'

volumes:
  postgres_data:
  static_volume:

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
  db:
    image: postgres:11-alpine
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_USER=${db_user}
    ports:
      - 5432:5432
  api: 
    build: .
    command: go run ./RestApiForGo/main.go
    restart: always
    volumes:
      - ./:/code
      - static_volume:/code/static
    env_file:
      - ./RestApiForGo/.env
    depends_on:
      - db
    ports:
      - 8080:8080
